load table of contents from body and scroll
libero/editor-client pull request #109
Opened 2020-09-18 12:04 UTC by ilya-zhuravel

2020-09-18 12:28 UTC, norisalsaadie approved these changes
Not too familiar with the code but I don't spot any obvious concerns

2020-09-18 13:13 UTC, NuclearRedeye requested changes
Some changes needed, also can break it by...
1. Select 'Acknowledgements'
2. Try and click anything else.
I think that might be because the ID is incorrect, but feel that it shouldn't stop the whole thing from working!

I also can't use the paragraph menu any more to create new headings, etc.

2020-09-18 13:13 UTC, NuclearRedeye commented on src/app/containers/manuscript/manuscript-toc.tsx
> +    { level: 1, title: 'Acknowledgements', id: 'acknowledgement' }
id should be 'acknowledgements'

2020-09-18 13:13 UTC, NuclearRedeye commented on src/app/containers/manuscript/manuscript-toc.tsx
> +    ...manuscriptBodyTOC,
There should be an entry here for 'main body' I think, which takes you to the start of the main body.

2020-09-22 08:13 UTC, NuclearRedeye requested changes
Good work, that's fixed those previous issues. I've found another issue which I think might be worth having a quick look at here, but if it turns out to be a rabbit hole we can address that under a new issue. Basically, if you copy/paste some content the duplicate entries in the TOC always take you to the first section, so I assume when you copy/paste it is also copying the ID and hence that causes the navigation to trip up a little.

2020-09-23 08:31 UTC, NuclearRedeye approved these changes
Tested locally and this is working well now.

2020-09-23 08:49 UTC, merged