Support for boxes in editor
libero/editor-client pull request #116
Opened 2020-10-05 13:48 UTC by ilya-zhuravel

This commit puts together the basics functionality. 
Some issues still persist one of which is references.

2020-10-05 16:09 UTC, norisalsaadie approved these changes

2020-10-06 10:23 UTC, Cooryd commented on src/app/components/reference-citation-editor-popup/index.tsx
> +    console.log('node selected');
Are these `console.log`s bing left in for debugging purposes?

2020-10-06 14:35 UTC, NuclearRedeye requested changes
Sorry for the delay...
1. Using insert from the menu doesn't work, and has caused a crash occasionally.
2. I noticed that running npm install adds a new dep, `bindings`, so this should be updated and committed.
3. The selection issue I noted earlier..
Otherwise, looking pretty good.

2020-10-06 14:35 UTC, NuclearRedeye commented on src/app/components/box-text/box-text-editor.tsx
> +        onSelectionChange(change.selection.$anchor.pos, change.selection.$head.pos);
I noticed I can only select text left to right, not right to left. It looks like it might be tied to this, might need to test if head < anchor.

2020-10-09 08:36 UTC, NuclearRedeye approved these changes
Tested locally, I think this is now good enough to merge for further feedback.

2020-10-09 08:43 UTC, merged