545 display figures
libero/editor-client pull request #121
Opened 2020-10-16 09:35 UTC by ilya-zhuravel

2020-10-16 14:52 UTC, NuclearRedeye requested changes
Looks good, just 2 minor cosmetic items to address.
1. The 'Figure Number' control focus style seems to thicken the border more than others.
2. The 'Title' and 'Legend' labels have a different background colour to the grey used for the figure.

2020-10-16 16:24 UTC, norisalsaadie commented on src/app/components/figure/index.tsx
> +    const offsetMap = StepMap.offset(this.getPos() + 2 + additionalOffset);
Not sure what the value 2 means here. Perhaps we can assign it a variable to make it more readable?

2020-10-16 16:25 UTC, norisalsaadie approved these changes

2020-10-19 11:14 UTC, NuclearRedeye approved these changes
Still see the issue with the extra think border on the title, but happy to let that minor cosmetic slide for now.

2020-10-19 11:44 UTC, merged