577 edit asset licenses
libero/editor-client pull request #129
Opened 2020-10-30 16:20 UTC by ilya-zhuravel

2020-11-02 09:19 UTC, norisalsaadie commented on src/app/components/figure/figure-license-editor.tsx
> +          {license.licenseType !== FIGURE_LICENSE_CC0 ? (
I believe this can be simplified using an && without needing to perform a ternary statement - not sure if it would play nicely with TypeScript or not

2020-11-02 09:23 UTC, norisalsaadie commented on src/app/components/figure/figure-license-editor.tsx
> +        {license.licenseType !== FIGURE_LICENSE_CC0 ? (
Same as the previous comment

2020-11-02 09:27 UTC, norisalsaadie approved these changes

2020-11-02 17:28 UTC, NuclearRedeye requested changes
Testing locally, first issue that I've picked up on is...
1. Go to [here](http://localhost:3000/?articleId=00104)
2. Scroll down to an asset license on a figure, add some extra text to the fields.
3. Hit add license.
Note, how it adds 2 licenses including a clone of the first.

2020-11-04 08:48 UTC, NuclearRedeye approved these changes
Tested locally, had a couple of instances where I can get it to throw an exception but I've not managed to come up with a solid reproducible case.
Other than that, a lot of code to comb through which I'll admit I've not done thoroughly but it's functionally good some I'm happy for it to go in.

2020-11-04 09:46 UTC, merged